# ═══════════════════════════════════════════════════════════════════════
#  app.py - CONSOLIDATED FINAL APPLICATION
# ═══════════════════════════════════════════════════════════════════════

import streamlit as st
import hashlib
import base64
import random # Keep random for recommendation page logic
import pandas as pd # Keep pandas for st.dataframe

# ─────────────────────────────────────────────────────────────────────────
# PAGE CONFIGURATION (Must be first)
# ─────────────────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="Introspective Immersion",
    page_icon="",
    layout="centered"
)

# ─────────────────────────────────────────────────────────────────────────
# CSS INJECTION AND UTILITY FUNCTIONS
# ─────────────────────────────────────────────────────────────────────────

def hide_default_navigation():
    """
    Injects CSS to hide the automatic links generated by Streamlit.
    (This is technically redundant if we only show the login, but harmless.)
    """
    st.markdown(
        """
        <style>
        .st-emotion-cache-18ni7ap { 
            display: none;
        }
        </style>
        """,
        unsafe_allow_html=True
    )

def get_base64_of_bin_file(bin_file):
    """Reads a local file and encodes it to a base64 string."""
    try:
        with open(bin_file, 'rb') as f:
            data = f.read()
        return base64.b64encode(data).decode()
    except FileNotFoundError:
        return None

# Call the CSS function immediately after config
hide_default_navigation()


# ─────────────────────────────────────────────────────────────────────────
# SESSION STATE INITIALIZATION
# ─────────────────────────────────────────────────────────────────────────

if 'logged_in' not in st.session_state:
    st.session_state.logged_in = False

if 'users' not in st.session_state:
    st.session_state.users = {} 

if 'current_user' not in st.session_state:
    st.session_state.current_user = None

if 'quiz_results' not in st.session_state:
    st.session_state.quiz_results = {}

if 'trope_results' not in st.session_state:
    st.session_state.trope_results = {}

if 'current_page' not in st.session_state:
    st.session_state.current_page = 'home'





# ─────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS (Retained for functionality)
# ─────────────────────────────────────────────────────────────────────────
def hash_password(password: str) -> str:
    return hashlib.sha256(password.encode()).hexdigest()

def check_credentials(username: str, password: str) -> bool:
    hashed_pass = hash_password(password)
    return st.session_state.users.get(username) == hashed_pass

def register_user(username: str, password: str) -> tuple[bool, str]:
    if username in st.session_state.users:
        return (False, "Username already taken")
    if len(password) < 6:
        return (False, "Password must be at least 6 characters long")
    
    st.session_state.users[username] = hash_password(password)
    st.session_state.quiz_results[username] = {} 
    st.session_state.trope_results[username] = {}
    return (True, "Registration successful! Please login.")

def calculate_archetype(results: dict[str, int]) -> tuple[str, int]:
    # ... (full function body needed here) ...
    if not results or all(v == 0 for v in results.values()): return ("Undetermined", 0)
    primary_archetype = max(results, key=results.get); max_score = results[primary_archetype]
    tied_archetypes = [k for k, v in results.items() if v == max_score]
    if len(tied_archetypes) > 1: return (f"Tied ({' & '.join(tied_archetypes)})", max_score)
    return (primary_archetype, max_score)

def calculate_trope(results: dict[str, int]) -> str:
    # ... (full function body needed here) ...
    if not results or all(v == 0 for v in results.values()): return "Undetermined"
    primary_trope = max(results, key=results.get); max_score = results[primary_trope]
    tied_tropes = [k for k, v in results.items() if v == max_score]
    if len(tied_tropes) > 1: return f"Tied ({' & '.join(tied_tropes)})"
    return primary_trope


# ─────────────────────────────────────────────────────────────────────────
# VIEW FUNCTIONS (Forms and Pages) - Logic Retained
# ─────────────────────────────────────────────────────────────────────────

def show_login_form():
    # ... (function body remains the same) ...
    st.subheader("Authentication")
    with st.form("login_form"):
        username = st.text_input("Username")
        password = st.text_input("Password", type="password")
        submitted = st.form_submit_button("Access Portal")
        
        if submitted:
            if check_credentials(username, password):
                st.session_state.logged_in = True
                st.session_state.current_user = username
                st.session_state.current_page = 'home'
                st.rerun()
            else:
                st.error("Invalid Username or Password. Denied access.")

def show_registration_form():
    # ... (function body remains the same) ...
    st.subheader("Registration")
    with st.form("registration_form"):
        new_username = st.text_input("Desired Username")
        new_password = st.text_input("Secure Password (min 6 chars)", type="password")
        submitted = st.form_submit_button("Register")
        
        if submitted:
            success, message = register_user(new_username, new_password)
            if success:
                st.success(message)
                st.session_state.login_tab_selected = True 
            else:
                st.error(message)

# --- HOME PAGE (UI elements removed) ---
def show_home_page():
    """
    Displays the central logo and a welcome message, removing all navigation buttons.
    """
    current_user = st.session_state.current_user
    
    # --- 1. Display Logo in the Center ---
    LOGO_FILENAME = 'logo.png'
    logo_base64 = get_base64_of_bin_file(LOGO_FILENAME)
    
    if logo_base64:
        col_img_left, col_img_center, col_img_right = st.columns([1, 2, 1])
        with col_img_center:
            st.markdown(f"""
                <div style="text-align: center; margin-bottom: 20px;">
                    <img src="data:image/png;base64,{logo_base64}" 
                         alt="Introspective Immersion Logo" 
                         style="max-width: 100%; height: auto; border-radius: 10px;">
                </div>
            """, unsafe_allow_html=True)
            
    st.success(f"Welcome back, **{current_user}**! Your session is active.")
    st.markdown("---")
    
    

# ─────────────────────────────────────────────────────────────────────────
# MAIN APPLICATION LOGIC (The Router)
# ─────────────────────────────────────────────────────────────────────────

def main():
    
    # FANCY TITLE (Always shown)
    st.markdown("""
        <h1 style='text-align: center; color: #E75480; font-family: Georgia, serif; font-size: 3em;'>
            Introspective Immersion 
        </h1>
        <h3 style='text-align: center; color: #808080;'>
            Find Your True Self
        </h3>
    """, unsafe_allow_html=True)

    
    if st.session_state.get('logged_in', False):
        
        # --- NO SIDEBAR BUTTONS ---

        # 2. Route the user based on the selected page (Logic preserved)
        if st.session_state.current_page == 'archetype':
            # You must have show_archetype_page() defined above
            st.warning("Archetype page functionality disabled in this version.") 
            # show_archetype_page() 
        elif st.session_state.current_page == 'personality':
            # You must have show_personality_page() defined above
            st.warning("Personality page functionality disabled in this version.") 
            # show_personality_page()
        elif st.session_state.current_page == 'recommendation':
            # You must have show_recommendation_page() defined above
            st.warning("Recommendation page functionality disabled in this version.") 
            # show_recommendation_page()
        else: # Default is 'home'
            show_home_page()
            
    else:
        # User is NOT LOGGED IN: Show Login/Registration
        tab1, tab2 = st.tabs(["Login", "Register"])
        
        with tab1:
            show_login_form()
        with tab2:
            show_registration_form()
            
        if 'login_tab_selected' in st.session_state:
            del st.session_state.login_tab_selected


if __name__ == "__main__":
    main()